import createPlotlyComponent from 'react-plotly.js/factory'
import Plotly from 'plotly.js-cartesian-dist-min'
import type { CorrelationsResponse, DistributionResponse, Histogram, OutlierFeature } from '../../types/eda'

const Plot = createPlotlyComponent(Plotly)
const font = { family: 'Inter, ui-sans-serif, system-ui, sans-serif', color: '#526071', size: 12 }
const config = { responsive: true, displaylogo: false, editable: false, scrollZoom: false, modeBarButtonsToRemove: ['lasso2d', 'select2d', 'autoScale2d', 'zoom2d', 'pan2d', 'zoomIn2d', 'zoomOut2d'] as never[] }
const histogramGeometry = (histogram: Histogram) => ({ centers: histogram.counts.map((_, i) => (histogram.bin_edges[i] + histogram.bin_edges[i + 1]) / 2), widths: histogram.counts.map((_, i) => histogram.bin_edges[i + 1] - histogram.bin_edges[i]), ranges: histogram.counts.map((_, i) => `${histogram.bin_edges[i].toLocaleString()} to ${histogram.bin_edges[i + 1].toLocaleString()}`) })

export function DistributionChart({ distribution, logView }: { distribution: DistributionResponse; logView: boolean }) {
  const histogram = logView && distribution.log1p_histogram ? distribution.log1p_histogram : distribution.histogram
  const geometry = histogramGeometry(histogram); const marker = logView ? Math.log1p(distribution.median) : distribution.median
  const unit = logView ? 'log1p-transformed value' : distribution.feature === 'MonetaryValue' ? 'Monetary value (GBP)' : ['Recency', 'CustomerLifetimeDays'].includes(distribution.feature) ? 'Days' : 'Count'
  return <Plot data={[{ type: 'bar', x: geometry.centers, y: histogram.counts, width: geometry.widths, marker: { color: '#607D94', line: { color: '#F8FAFC', width: .5 } }, customdata: geometry.ranges.map((range, i) => [range, histogram.counts[i] / distribution.count * 100]), hovertemplate: '<b>Range:</b> %{customdata[0]}<br>Customers: %{y:,}<br>Share: %{customdata[1]:.2f}%<extra></extra>' }]} layout={{ autosize: true, height: 390, margin: { l: 58, r: 22, t: 12, b: 58 }, paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)', font, bargap: 0, showlegend: false, xaxis: { title: { text: unit }, gridcolor: '#EEF2F5', zeroline: false, tickprefix: !logView && distribution.feature === 'MonetaryValue' ? '£' : undefined }, yaxis: { title: { text: 'Customers' }, gridcolor: '#E7ECF0', zeroline: false }, shapes: [{ type: 'line', x0: marker, x1: marker, y0: 0, y1: 1, yref: 'paper', line: { color: '#8066A8', width: 2, dash: 'dash' } }], annotations: [{ x: marker, y: 1, yref: 'paper', text: 'Median', showarrow: false, yshift: 10, font: { color: '#6A4F91', size: 11 } }] }} config={config} useResizeHandler style={{ width: '100%', height: '390px' }} />
}

export function CorrelationHeatmap({ data }: { data: CorrelationsResponse }) {
  return <Plot data={[{ type: 'heatmap', x: data.features, y: data.features, z: data.matrix, zmin: -1, zmax: 1, zmid: 0, colorscale: [[0, '#526D82'], [.5, '#F4F6F8'], [1, '#8066A8']], colorbar: { title: { text: 'Pearson r' }, thickness: 12 }, text: data.matrix.map((row) => row.map((value) => value.toFixed(2))), texttemplate: '%{text}', hovertemplate: '<b>%{y}</b> and <b>%{x}</b><br>Pearson correlation: %{z:.3f}<extra></extra>' }]} layout={{ autosize: true, height: 570, margin: { l: 145, r: 70, t: 15, b: 135 }, paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)', font, xaxis: { tickangle: -38, side: 'bottom' }, yaxis: { autorange: 'reversed' } }} config={config} useResizeHandler style={{ width: '100%', height: '570px' }} />
}

export function OutlierPercentageChart({ features }: { features: OutlierFeature[] }) {
  const rows = [...features].sort((a, b) => b.outlier_percentage - a.outlier_percentage)
  return <Plot data={[{ type: 'bar', orientation: 'h', x: rows.map((row) => row.outlier_percentage), y: rows.map((row) => row.feature), marker: { color: rows.map((row) => row.outlier_percentage === 0 ? '#CCD5DC' : '#607D94') }, customdata: rows.map((row) => [row.outlier_count, row.lower_bound, row.upper_bound]), text: rows.map((row) => `${row.outlier_percentage.toFixed(1)}%`), textposition: 'outside', cliponaxis: false, hovertemplate: '<b>%{y}</b><br>Outliers: %{customdata[0]:,}<br>Share: %{x:.2f}%<br>IQR bounds: %{customdata[1]:,.2f} to %{customdata[2]:,.2f}<extra></extra>' }]} layout={{ autosize: true, height: 440, margin: { l: 165, r: 70, t: 10, b: 50 }, paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)', font, showlegend: false, xaxis: { title: { text: 'Customers flagged by Tukey rule (%)' }, gridcolor: '#E7ECF0', zeroline: false }, yaxis: { autorange: 'reversed', automargin: true }, bargap: .28 }} config={config} useResizeHandler style={{ width: '100%', height: '440px' }} />
}

export function TransformationComparisonChart({ distribution }: { distribution: DistributionResponse }) {
  if (!distribution.log1p_histogram) return null
  const original = histogramGeometry(distribution.histogram); const transformed = histogramGeometry(distribution.log1p_histogram)
  return <Plot data={[{ type: 'bar', x: original.centers, y: distribution.histogram.counts, width: original.widths, marker: { color: '#607D94' }, xaxis: 'x', yaxis: 'y', hovertemplate: 'Original range: %{x:,.2f}<br>Customers: %{y:,}<extra></extra>' }, { type: 'bar', x: transformed.centers, y: distribution.log1p_histogram.counts, width: transformed.widths, marker: { color: '#8066A8' }, xaxis: 'x2', yaxis: 'y2', hovertemplate: 'log1p value: %{x:.3f}<br>Customers: %{y:,}<extra></extra>' }]} layout={{ autosize: true, height: 390, margin: { l: 55, r: 22, t: 35, b: 55 }, paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)', font, showlegend: false, xaxis: { domain: [0, .46], title: { text: 'Original scale' }, gridcolor: '#EEF2F5' }, yaxis: { title: { text: 'Customers' }, gridcolor: '#E7ECF0' }, xaxis2: { domain: [.54, 1], title: { text: 'log1p-transformed value' }, gridcolor: '#EEF2F5' }, yaxis2: { anchor: 'x2', gridcolor: '#E7ECF0' }, annotations: [{ x: .23, y: 1.1, xref: 'paper', yref: 'paper', text: 'Original distribution', showarrow: false }, { x: .77, y: 1.1, xref: 'paper', yref: 'paper', text: 'Transformed distribution', showarrow: false }] }} config={config} useResizeHandler style={{ width: '100%', height: '390px' }} />
}
