import createPlotlyComponent from 'react-plotly.js/factory'
import Plotly from 'plotly.js-cartesian-dist-min'
import type { ComparisonItem, ValidationCandidate } from '../../types/modelEvaluation'
const Plot=createPlotlyComponent(Plotly)
const font={family:'Inter, ui-sans-serif, system-ui, sans-serif',color:'#526071',size:11}
const config={responsive:true,displaylogo:false,editable:false,scrollZoom:false,modeBarButtonsToRemove:['lasso2d','select2d','toImage','zoom2d','pan2d'] as never[]}
const candidateName=(row:ComparisonItem)=>`${row.algorithm} ${row.configuration}`
export function MetricChart({rows,metric,label,direction}:{rows:ComparisonItem[];metric:'silhouette_score'|'davies_bouldin'|'calinski_harabasz';label:string;direction:string}) { const ordered=[...rows]; return <Plot data={[{type:'bar',orientation:'h',x:ordered.map(r=>r[metric]),y:ordered.map(candidateName),marker:{color:ordered.map(r=>r.algorithm==='K-Means'&&r.configuration==='k=3'?'#334E68':'#AAB6C0')},text:ordered.map(r=>r[metric].toFixed(metric==='calinski_harabasz'?1:3)),textposition:'outside',cliponaxis:false,customdata:ordered.map(r=>[r.coverage_percentage,r.noise_percentage,r.algorithm==='K-Means'&&r.configuration==='k=3'?'Selected final model':'Evaluated alternative']),hovertemplate:'<b>%{y}</b><br>'+label+': %{x:.3f}<br>Coverage: %{customdata[0]:.1f}%<br>Noise: %{customdata[1]:.1f}%<br>%{customdata[2]}<extra></extra>'}]} layout={{autosize:true,height:300,margin:{l:185,r:65,t:10,b:50},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font,showlegend:false,xaxis:{title:{text:`${label} (${direction})`},gridcolor:'#E7ECF0',zeroline:false},yaxis:{autorange:'reversed'}}} config={config} useResizeHandler style={{width:'100%',height:'300px'}}/> }
export function CoverageChart({rows}:{rows:ComparisonItem[]}) { return <Plot data={[{type:'bar',orientation:'h',name:'Modeled coverage',x:rows.map(r=>r.coverage_percentage),y:rows.map(candidateName),marker:{color:'#526D82'},hovertemplate:'Modeled coverage: %{x:.1f}%<extra></extra>'},{type:'bar',orientation:'h',name:'DBSCAN noise',x:rows.map(r=>r.noise_percentage),y:rows.map(candidateName),marker:{color:'#D3DAE0'},hovertemplate:'Noise: %{x:.1f}%<extra></extra>'}]} layout={{barmode:'stack',autosize:true,height:300,margin:{l:185,r:25,t:15,b:55},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font,legend:{orientation:'h',y:1.12},xaxis:{range:[0,100],title:{text:'Customers (%)'},gridcolor:'#E7ECF0'},yaxis:{autorange:'reversed'}}} config={config} useResizeHandler style={{width:'100%',height:'300px'}}/> }
export function StabilityChart({rows}:{rows:ValidationCandidate[]}) { return <Plot data={[{type:'bar',x:rows.map(r=>`k=${r.k}`),y:rows.map(r=>r.subsampling_stability.mean_ari),error_y:{type:'data',array:rows.map(r=>r.subsampling_stability.standard_deviation_ari),visible:true,color:'#526071'},marker:{color:rows.map(r=>r.k===3?'#334E68':'#AAB6C0')},text:rows.map(r=>r.subsampling_stability.mean_ari.toFixed(3)),textposition:'outside',hovertemplate:'Mean ARI: %{y:.4f}<extra></extra>'}]} layout={{autosize:true,height:310,margin:{l:60,r:25,t:20,b:55},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font,yaxis:{range:[0,1.05],title:{text:'Mean subsampling ARI'},gridcolor:'#E7ECF0'},xaxis:{title:{text:'Candidate'}}}} config={config} useResizeHandler style={{width:'100%',height:'310px'}}/> }
export function SensitivityChart({rows}:{rows:ValidationCandidate[]}) { return <Plot data={[{type:'bar',x:rows.map(r=>`k=${r.k}`),y:rows.map(r=>r.feature_sensitivity.ari_vs_primary),marker:{color:rows.map(r=>r.k===3?'#334E68':'#AAB6C0')},text:rows.map(r=>r.feature_sensitivity.ari_vs_primary.toFixed(3)),textposition:'outside',hovertemplate:'Feature-substitution ARI: %{y:.4f}<extra></extra>'}]} layout={{autosize:true,height:310,margin:{l:60,r:25,t:20,b:55},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font,yaxis:{range:[0,1],title:{text:'ARI'},gridcolor:'#E7ECF0'},xaxis:{title:{text:'Candidate'}}}} config={config} useResizeHandler style={{width:'100%',height:'310px'}}/> }
