import { useCallback, useState } from 'react'
import { AnalyticalFigure } from '../components/analysis/AnalyticalFigure'
import { CorrelationHeatmap, DistributionChart, OutlierPercentageChart, TransformationComparisonChart } from '../components/charts/EdaCharts'
import { PageHeader } from '../components/layout/PageHeader'
import { DataState } from '../components/ui/DataState'
import { FeatureSelector } from '../components/ui/FeatureSelector'
import { Section } from '../components/ui/Section'
import { useApiResource } from '../hooks/useApiResource'
import { getCorrelations, getDistribution, getOutliers } from '../services/edaApi'
import type { DistributionResponse, EdaFeature, OutlierFeature } from '../types/eda'
import { formatCurrency, formatDecimal, formatInteger, formatPercent } from '../utils/formatters'

const FEATURES: readonly EdaFeature[] = ['Recency', 'Frequency', 'MonetaryValue', 'UniqueProducts', 'CustomerLifetimeDays']
const LOG_FEATURES: readonly EdaFeature[] = ['Frequency', 'MonetaryValue', 'UniqueProducts']
const formatFeatureValue = (feature: string, value: number) => feature === 'MonetaryValue' ? formatCurrency(value) : ['Recency', 'CustomerLifetimeDays'].includes(feature) ? `${formatInteger(value)} days` : formatInteger(value)
const skewClass = (value: number) => Math.abs(value) < .5 ? 'relatively symmetric' : Math.abs(value) <= 1 ? 'moderately skewed' : 'strongly skewed'

function DistributionWorkspace() {
  const [feature, setFeature] = useState<EdaFeature>('Recency')
  const [logView, setLogView] = useState(false)
  const loader = useCallback((signal?: AbortSignal) => getDistribution(feature, signal), [feature])
  const resource = useApiResource(loader)
  const selectFeature = (next: EdaFeature) => { setFeature(next); setLogView(false) }
  return <><FeatureSelector label="Distribution feature" options={FEATURES} value={feature} onChange={selectFeature} />{resource.loading && <DataState state="loading" message={`Loading the ${feature} distribution.`} />}{resource.error && <DataState state="error" message={`The ${feature} distribution is unavailable.`} onRetry={resource.retry} />}{resource.data && <DistributionResult data={resource.data} logView={logView} setLogView={setLogView} />}</>
}

function DistributionResult({ data, logView, setLogView }: { data: DistributionResponse; logView: boolean; setLogView: (value: boolean) => void }) {
  const finding = `${data.feature} is ${skewClass(data.skewness)} (skewness ${formatDecimal(data.skewness, 2)}); its mean is ${formatFeatureValue(data.feature, data.mean)} compared with a median of ${formatFeatureValue(data.feature, data.median)}.`
  return <div className="distribution-result">{data.log1p_histogram && <div className="view-toggle" role="group" aria-label={`${data.feature} display scale`}><button type="button" className={!logView ? 'view-toggle__active' : ''} aria-pressed={!logView} onClick={() => setLogView(false)}>Original scale</button><button type="button" className={logView ? 'view-toggle__active' : ''} aria-pressed={logView} onClick={() => setLogView(true)}>log1p transformed</button></div>}<div className="distribution-layout"><AnalyticalFigure id="feature-distribution" title={`${data.feature} distribution`} description={`${formatInteger(data.count)} customer profiles shown using backend-provided histogram bins${logView ? ' on a log1p-transformed x-axis' : ''}.`} keyFinding={finding} interpretation={data.log_display_recommended ? 'The strong right tail supports compressing this feature with log1p before distance-based modeling. The display toggle does not retrain or change the model.' : 'This feature remains in its original form before standardization because the final preprocessing policy does not apply log1p to it.'} howToRead="Bar height is the number of customers in each backend-defined bin. The dashed vertical line marks the median. |skewness| below 0.5 is described as relatively symmetric, 0.5 to 1 as moderate skew, and above 1 as strong skew." limitation="Skewness summarizes asymmetry but does not test normality or determine preprocessing by itself."><DistributionChart distribution={data} logView={logView} /></AnalyticalFigure><aside className="statistics-panel" aria-label={`${data.feature} summary statistics`}><h3>Summary statistics</h3><dl>{[['Count', formatInteger(data.count)], ['Minimum', formatFeatureValue(data.feature, data.minimum)], ['Q1', formatFeatureValue(data.feature, data.quartiles.q1)], ['Median', formatFeatureValue(data.feature, data.median)], ['Mean', formatFeatureValue(data.feature, data.mean)], ['Q3', formatFeatureValue(data.feature, data.quartiles.q3)], ['Maximum', formatFeatureValue(data.feature, data.maximum)], ['Standard deviation', formatFeatureValue(data.feature, data.standard_deviation)], ['Skewness', formatDecimal(data.skewness, 3)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></aside></div></div>
}

export function ExploratoryAnalysisPage() {
  const correlations = useApiResource(getCorrelations)
  const outliers = useApiResource(getOutliers)
  return <><PageHeader eyebrow="Exploratory analysis" title="Customer Behavior Exploration" description="Customer-level behavioral features were examined for distribution shape, correlation, skewness, and extreme observations before clustering." /><div className="eda-page"><div className="research-section-heading"><span>01</span><div><h2>Behavioral distributions</h2><p>Inspect one customer feature at a time and compare original and transformed views where available.</p></div></div><DistributionWorkspace /><div className="research-section-heading"><span>02</span><div><h2>Relationships & feature selection</h2><p>Review linear relationships alongside the behavioral reasoning used to select the final clustering variables.</p></div></div>{correlations.loading && <DataState state="loading" message="Loading the Pearson correlation matrix." />}{correlations.error && <DataState state="error" message="Correlation evidence is unavailable." onRetry={correlations.retry} />}{correlations.data && <><AnalyticalFigure id="correlation-heatmap" title="Behavioral feature correlations" description="Pearson correlations across all customer-level numerical features returned by the analytics API." keyFinding={correlationFinding(correlations.data.strongest_correlation_pairs)} interpretation={`${correlations.data.interpretation.primary_feature_note} Correlation was considered together with behavioral meaning rather than used as an automatic feature-selection rule.`} howToRead="Each cell shows Pearson r for a pair of features. Values near 1 indicate positive linear association, values near -1 indicate negative association, and values near zero indicate weak linear association." limitation={correlations.data.interpretation.guidance}><CorrelationHeatmap data={correlations.data} /></AnalyticalFigure><FeatureSelection /></>}
      <div className="research-section-heading"><span>03</span><div><h2>Outliers & transformation</h2><p>Document extreme observations and how transformation reduced their influence without deleting customers.</p></div></div>{outliers.loading && <DataState state="loading" message="Loading outlier summaries." />}{outliers.error && <DataState state="error" message="Outlier evidence is unavailable." onRetry={outliers.retry} />}{outliers.data && <OutlierWorkspace features={outliers.data.features} method={outliers.data.method} interpretation={outliers.data.interpretation} />}<TransformationWorkspace /><PreprocessingConclusion correlations={correlations.data?.strongest_correlation_pairs ?? []} outliers={outliers.data?.features ?? []} /></div></>
}

function correlationFinding(pairs: { feature_a: string; feature_b: string; correlation: number }[]) {
  const monetary = pairs.find((pair) => new Set([pair.feature_a, pair.feature_b]).has('MonetaryValue') && new Set([pair.feature_a, pair.feature_b]).has('TotalItems'))
  const pair = monetary ?? pairs[0]
  return `${pair.feature_a} and ${pair.feature_b} have a Pearson correlation of ${formatDecimal(pair.correlation, 3)}. This relationship was considered when limiting redundant volume measures in the primary feature set.`
}

function FeatureSelection() {
  return <Section title="Final feature selection" description="The primary matrix balances complementary customer behaviors with redundancy and data-type considerations."><div className="selection-columns"><div><h3>Selected behavioral dimensions</h3><ul><li>Recency</li><li>Frequency</li><li>MonetaryValue</li><li>UniqueProducts</li><li>CustomerLifetimeDays</li></ul></div><div><h3>Not selected for the primary matrix</h3><dl><div><dt>TotalItems</dt><dd>Strongly correlated with MonetaryValue.</dd></div><div><dt>AverageOrderValue and AverageItemsPerOrder</dt><dd>Retained as secondary behavioral measures for interpretation and sensitivity work.</dd></div><div><dt>Country</dt><dd>Categorical and highly imbalanced, so it remains descriptive rather than distance-based.</dd></div></dl></div></div></Section>
}

function OutlierWorkspace({ features, method, interpretation }: { features: OutlierFeature[]; method: string; interpretation: string }) {
  const [selected, setSelected] = useState(features[0]?.feature ?? '')
  const current = features.find((feature) => feature.feature === selected) ?? features[0]
  const largest = [...features].sort((a, b) => b.outlier_percentage - a.outlier_percentage)[0]
  return <div className="outlier-layout"><AnalyticalFigure id="outlier-percentage" title="Outliers by behavioral feature" description={method} keyFinding={`${largest.feature} has the highest Tukey-rule outlier share at ${formatPercent(largest.outlier_percentage)}, representing ${formatInteger(largest.outlier_count)} customers.`} interpretation={`${interpretation} Automatic deletion could remove meaningful high-volume or wholesale behavior, so the project used transformation and robustness comparisons instead.`} howToRead="Bars show the percentage of customers outside each feature's 1.5 × IQR bounds. Hover provides counts and calculated bounds." limitation="An IQR flag identifies statistical extremity, not data-entry error or invalid customer behavior."><OutlierPercentageChart features={features} /></AnalyticalFigure><Section title="Outlier detail" description="Select a feature to inspect its bounds and representative extreme customers."><label className="select-label" htmlFor="outlier-feature">Behavioral feature</label><select id="outlier-feature" value={current.feature} onChange={(event) => setSelected(event.target.value)}>{features.map((feature) => <option key={feature.feature}>{feature.feature}</option>)}</select><dl className="outlier-stat-list"><div><dt>Q1 / Q3</dt><dd>{formatFeatureValue(current.feature, current.q1)} / {formatFeatureValue(current.feature, current.q3)}</dd></div><div><dt>IQR</dt><dd>{formatFeatureValue(current.feature, current.iqr)}</dd></div><div><dt>Lower / upper bound</dt><dd>{formatFeatureValue(current.feature, current.lower_bound)} / {formatFeatureValue(current.feature, current.upper_bound)}</dd></div><div><dt>Flagged customers</dt><dd>{formatInteger(current.outlier_count)} ({formatPercent(current.outlier_percentage)})</dd></div></dl><div className="research-table-wrap"><table className="research-table compact-table"><thead><tr><th scope="col">Customer ID</th><th scope="col">{current.feature}</th></tr></thead><tbody>{current.representative_extreme_customers.map((customer) => <tr key={customer.CustomerID}><th scope="row">{formatInteger(customer.CustomerID)}</th><td>{formatFeatureValue(current.feature, customer.value)}</td></tr>)}</tbody></table></div><p className="table-note">Representative extremes are not automatically invalid observations.</p></Section></div>
}

function TransformationWorkspace() {
  const [feature, setFeature] = useState<EdaFeature>('MonetaryValue')
  const loader = useCallback((signal?: AbortSignal) => getDistribution(feature, signal), [feature])
  const resource = useApiResource(loader)
  return <div className="transformation-workspace"><FeatureSelector label="Transformation comparison feature" options={LOG_FEATURES} value={feature} onChange={setFeature} />{resource.loading && <DataState state="loading" message={`Loading ${feature} transformation evidence.`} />}{resource.error && <DataState state="error" message="Transformation comparison is unavailable." onRetry={resource.retry} />}{resource.data && <AnalyticalFigure id="transformation-comparison" title="Original and log1p distributions" description={`${feature} shown with the backend-provided original and transformed histogram summaries.`} keyFinding={`${feature} has original-scale skewness of ${formatDecimal(resource.data.skewness, 2)}; log1p compresses the long right tail for distance-based modeling.`} interpretation="The transformation reduces the numerical dominance of unusually large purchase behavior while preserving customer ordering and all observations." howToRead="The left panel uses original units. The right panel uses log(1 + x), so its x-axis values are transformed and should not be read as currency or raw counts." limitation="The visual comparison demonstrates compression, not proof that transformed values are normally distributed."><TransformationComparisonChart distribution={resource.data} /></AnalyticalFigure>}</div>
}

function PreprocessingConclusion({ correlations, outliers }: { correlations: { feature_a: string; feature_b: string; correlation: number }[]; outliers: OutlierFeature[] }) {
  const monetary = correlations.find((pair) => [pair.feature_a, pair.feature_b].includes('MonetaryValue') && [pair.feature_a, pair.feature_b].includes('TotalItems'))
  const largest = [...outliers].sort((a, b) => b.outlier_percentage - a.outlier_percentage)[0]
  return <Section title="Why preprocessing was necessary" description="Exploratory evidence informed the fixed modeling pipeline." tone="quiet"><div className="method-note"><p>Frequency, MonetaryValue, and UniqueProducts showed strong right skew, so log1p was used to reduce the influence of their long upper tails without removing customers. StandardScaler then placed the five selected dimensions on comparable numerical scales before K-Means.</p><p>{monetary ? `MonetaryValue and TotalItems had Pearson r=${formatDecimal(monetary.correlation, 3)}, supporting the decision not to use both primary volume measures together. ` : ''}{largest ? `${largest.feature} had the largest IQR-flagged share at ${formatPercent(largest.outlier_percentage)}. ` : ''}Extreme observations were retained and evaluated through transformation and robustness testing rather than assumed to be invalid.</p></div></Section>
}
